# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'app_1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app_1
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
  pod 'Alamofire', '~> 4.5'
  pod 'FSCalendar'
  pod 'Firebase/Database' 
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Segmentio', '~> 2.1'
  pod 'AttributedTextView', '~> 0.5.1'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if  target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
